- id: url:https://www.thestar.com/opinion/contributors/it-s-time-to-defund-big-tech-and-empower-communities/article_60361bf3-a85c-5598-aac4-798f006f9c42.html
  type: article

- id: url:https://archivaria.ca/index.php/archivaria/article/view/13628
  type: paper

- id: url:https://archivaria.ca/index.php/archivaria/article/view/13628
  type: paper

- id: doi:10.1016/j.infsof.2023.107163
  type: paper
  image: images/chocolates_judgment.jpg

- id: doi:10.1145/3579462
  type: journal

- id: doi:10.21428/bf6fb269.541455de
  image: images/limits 2023.png
  date: '2023-06-14'
  tags:
    - limits 2023

- id: doi:10.1016/j.ecoinf.2022.101918
  type: journal

- id: doi:10.1007/s00799-021-00311-0
  type: paper

- id: doi:10.1109/MS.2019.2944784
  type: journal

- id: doi:10.1145/3608115
  type: journal

- id: doi:10.1145/3371906
  type: journal

- id: doi:10.1002/asi.24209
  type: journal

- id: doi:10.4230/DagRep.9.7.40
  type: paper

- id: doi:10.1002/asi.24048
  type: paper

- id: doi:10.1016/j.jss.2017.12.026
  type: paper

- id: doi:10.1002/asi.23881
  type: paper

- id: doi:10.4230/DagMan.6.1.1
  type: paper

- id: doi:10.1109/MS.2015.158
  type: paper

- id: doi:10.1108/OCLC-06-2014-0026
  type: paper

- id: doi:10.1108/OCLC-06-2014-0025
  type: paper

- id: doi:10.1145/3500868.3559399
  type: paper

- id: doi:10.1145/3406865.3418593
  type: paper

- id: doi:10.1145/3384772.3385141
  type: paper
  
- id: doi:10.1109/ESEM.2019.8870161
  type: paper
  
- id: doi:10.1109/TechDebt.2019.00011
  type: paper
  
- id: doi:10.48550/arXiv.1906.02266
  type: paper

- id: url:https://www.derstandard.at/story/2000114033073/ein-neuer-kompass-fuer-die-digitale-zukunft
  type: article

- id: doi:10.1109/MS.2018.110154908
  type: paper

- id: doi:10.1002/asi.23807
  type: paper

- id: doi:10.1109/RE.2018.00-23
  type: paper
- id: doi:10.1109/RE.2018.00038
  type: paper
- id: doi:10.1145/3194164.3194171
  type: paper
- id: doi:10.1145/3183377.3183382
  type: paper
- id: doi:10.1109/JCDL.2017.7991565
  type: paper
- id: doi:10.1109/ICSE-SEIS.2017.2
  type: paper
- id: doi:10.2991/ict4s-16.2016.20
  type: paper
- id: doi:10.1145/2889160.2889217
  type: paper

- id: doi:10.1109/ICSE.2015.179
  type: paper
  
- id: url:https://hdl.handle.net/11353/10.429547
  type: paper
  date: '2015-04-16'
  
- id: url:https://hdl.handle.net/11353/10.429553
  type: paper
  date: '2015-04-16'

- id: doi:10.1007/978-3-319-12823-8_1
  type: paper
- id: doi:10.1007/978-3-319-12823-8_1
  type: paper
- id: doi:10.1109/JCDL.2014.6970207
  type: paper
- id: doi:10.1145/2467696.2467719  
  type: paper
- id: doi:10.1145/2480362.2480637
  type: paper
  
- id: url:https://hdl.handle.net/11353/10.378051
  type: paper
  date: '2013-01-01'
  
- id: url:https://hdl.handle.net/11353/10.378091
  type: paper
  date: '2013-01-01'

- id: url:https://hdl.handle.net/11353/10.429621  
  type: paper
  date: '2015-06-03'
  
- id: url:http://hdl.handle.net/2142/73794
  type: paper
  date: '2015-03-15'
  
- id: url:https://ppig.org/papers/2020-ppig-31st-becker/
  type: paper
  date: '2020-01-01'

- id: doi:10.1109/CHASE.2017.6
  type: paper
- id: doi:10.1109/BigData.2016.7840982
  type: paper
  
- id: url:http://ceur-ws.org/Vol-1686/
  type: paper
  date: '2016-09-12'
  
- id: url:http://ceur-ws.org/Vol-1416/
  type: paper
  date: '2015-08-24'
  
- id: url:http://eprints.hud.ac.uk/id/eprint/24945/
  type: paper
  date: '2015-07-13'
  
- id: doi:10.1109/EDOCW.2014.44
  type: paper
  
- id: url:https://techotherwise.pubpub.org/cscw20
  title: 'Contributions to the CSCW 2020 Workshop: Collective Organizing and Social Responsibility'
  type: paper
  date: '2020-10-15'
  authors:
  - Devansh Saxena
  - Erhardt Graeff
  - Shion Guha
  - EunJeong Cheon
  - Pedro Reynolds-Cuellar
  - Dawn Walker
  - Kenneth R. Fleischmann
  
- id: url:https://techotherwise.pubpub.org/pdc20
  type: paper
  date: '2020-05-20'
  
- id: url:http://benchmark-dp.org/caiwipres/
  type: paper
  date: '2020-01-01'
  
- id: url:https://digitalpreservationchallenges.wordpress.com/
  type: paper
  date: '2013-08-24'

- id: doi:10.21428/93b2c832.e0100a3f
  type: paper

- id: doi:10.1145/3500868.3559399
  type: paper
