- id: doi:10.1016/j.infsof.2023.107163
  type: paper
  image: images/chocolates_judgment.jpg

- id: doi:10.1145/3579462
  type: journal

- id: doi:10.21428/bf6fb269.541455de
  image: images/limits 2023.png
  date: '2023-06-14'
  tags:
    - limits 2023

- id: doi:10.1016/j.ecoinf.2022.101918
  type: paper

- id: url:https://arxiv.org/abs/1901.07024
  type: paper
