- id: doi:10.1016/j.infsof.2023.107163
  type: paper
  image: images/chocolates_judgment.jpg

- id: doi:10.1145/3579462
  type: journal

- id: doi:10.21428/bf6fb269.541455de
  image: images/limits 2023.png
  date: '2023-06-14'
  tags:
    - limits 2023

- id: doi:10.1016/j.ecoinf.2022.101918
  type: paper

- id: url:https://arxiv.org/abs/1901.07024
  type: paper

- id: url:https://www.thestar.com/opinion/contributors/it-s-time-to-defund-big-tech-and-empower-communities/article_60361bf3-a85c-5598-aac4-798f006f9c42.html
  type: paper

- id: url:https://www.derstandard.at/story/2000114033073/ein-neuer-kompass-fuer-die-digitale-zukunft
  type: paper

- id: doi: 10.1016/j.infsof.2023.107163
  type: paper

- id: doi:10.1007/s00799-021-00311-0
  type: paper
