- id: url:https://www.thestar.com/opinion/contributors/it-s-time-to-defund-big-tech-and-empower-communities/article_60361bf3-a85c-5598-aac4-798f006f9c42.html
  type: article

- id: doi:10.1016/j.infsof.2023.107163
  type: paper
  image: images/chocolates_judgment.jpg

- id: doi:10.1145/3579462
  type: journal

- id: doi:10.21428/bf6fb269.541455de
  image: images/limits 2023.png
  date: '2023-06-14'
  tags:
    - limits 2023

- id: doi:10.1016/j.ecoinf.2022.101918
  type: journal

- id: doi:10.1007/s00799-021-00311-0
  type: paper

- id: doi:10.1109/MS.2019.2944784
  type: journal

- id: doi:10.1145/3608115
  type: journal

- id: doi:10.1145/3371906
  type: journal

- id: doi:10.1002/asi.24209
  type: journal

- id: doi:10.4230/DagRep.9.7.40
  type: paper



